english = {
    1: 'Settings',
    2: 'Log out',
    3: 'Hello',
    4: 'Welcome',
    5: 'Good Morning',
    6: 'Good Night',
    7: 'It is',
    8: 'Weather',
    9: 'outside.',
    10: 'Add to List',
    11: 'Weather in',
    12: 'Your Movies',
    13: 'Calendar',
    14: 'Install App',
    15: 'Enable Notifications',
    16: 'User',
    17: 'Username',
    18: 'Password',
    19: 'Home',
    20: 'Please save your settings at the bottom',
    21: 'Your Profile',
    22: 'Weather loading...',
    23: 'Darkmode',
    24: 'Lightmode',
    25: 'Select a theme',
    26: 'Your role is:',
    27: 'Your Rooms',
    28: 'Lights',
    29: 'Temperature',
    30: 'Lists',
    31: 'Administrator Settings',
    32: 'Be careful, read the docs',
    33: 'Add a new user',
    34: 'Confirm',
    35: 'Select a role for the new User',
    36: 'Administrator',
    37: 'User',
    38: 'Role',
    39: 'Warning',
    40: 'Choose a language',
    41: 'English',
    42: 'German',
    43: 'Profile',
    44: 'Test completed',
    45: 'The weather'
}