en = {
    1: 'Settings',
    2: 'Log out',
    3: 'Hello',
    4: 'Welcome',
    5: 'Good Morning',
    6: 'Good Night',
    7: 'Your Home',
    8: 'Weather',
    9: 'Your Lists',
    10: 'Add to List',
    11: 'Weather in',
    12: 'Your Movies',
    13: 'Calendar',
    14: 'Install App',
    15: 'Enable Notifications',
    16: 'User',
    17: 'Username',
    18: 'Password',
    19: 'Home'
}