german = {
    1: 'Einstellungen',
    2: 'Ausloggen',
    3: 'Hallo',
    4: 'Willkommen',
    5: 'Guten Morgen',
    6: 'Gute Nacht',
    7: 'Es ist',
    8: 'Wetter',
    9: 'draußen.',
    10: 'Zur Liste hinzufügen',
    11: 'Wetter in',
    12: 'Deine Filme',
    13: 'Kalendar',
    14: 'App installieren',
    15: 'Notifications einschalten',
    16: 'Nutzer',
    17: 'Nutzername',
    18: 'Passwort',
    19: 'Home',
    20: 'Bitte speichere deine Einstellungen unten',
    21: 'Dein Profil',
    22: 'Wetter lädt...',
    23: 'Darkmode',
    24: 'Lightmode',
    25: 'Wähle ein Theme',
    26: 'Deine Rolle ist:',
    27: 'Deine Räume',
    28: 'Lampen',
    29: 'Temperatur',
    30: 'Listen',
    31: 'Administrator Einstellungen',
    32: 'Sei vorsichtig, lies die Docs',
    33: 'Nutzer hinzufügen',
    34: 'Bestätigen',
    35: 'Wähle eine Rolle für den neuen Nutzer',
    36: 'Administrator',
    37: 'Nutzer',
    38: 'Rolle',
    39: 'Warnung',
    40: 'Wähle eine Sprache',
    41: 'Englisch',
    42: 'Deutsch',
    43: 'Profil'
}